from typing import Optional, Dict, List
from pydantic import BaseModel, Field


class HPI(BaseModel):
    onset: Optional[str] = Field(None, description="When the symptom started")
    location: Optional[str] = Field(None, description="Where exactly the symptom is located")
    duration: Optional[str] = Field(None, description="How long episodes last or if it is constant")
    character: Optional[str] = Field(None, description="What the pain feels like (sharp, dull, pressure, etc.)")
    severity: Optional[str] = Field(None, description="Pain scale severity (e.g., 7/10 or 'severe')")
    aggravating: Optional[str] = Field(None, description="What makes the symptoms worse")
    relieving: Optional[str] = Field(None, description="What helps relieve the symptoms")


class ClinicalBrief(BaseModel):
    chief_complaint: str
    hpi: HPI
    ros: Dict[str, List[str]]
    generated_at: str
    # FIX 3: LLM-generated clinical narrative — no longer a raw copy-paste
    narrative: Optional[str] = Field(
        None,
        description="A concise, clinically-worded summary generated by the LLM."
    )


class ClinicalStateExtraction(BaseModel):
    chief_complaint: Optional[str] = Field(None, description="The main reason for the visit")
    hpi: HPI = Field(default_factory=HPI)
    ros: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Review of systems, keys are system names, values are list of findings"
    )
    emergency_detected: bool = Field(
        False,
        description="True ONLY if the patient mentions life-threatening symptoms"
    )